# Generated by Django 5.1.3 on 2024-11-30 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart_product_photo_cart_product_star_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.RenameField(
            model_name='chathistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
